In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('data.csv')
df.head(9)

    Age   Salary Department
0  25.0  25000.0         HR
1  26.0  27000.0         IT
2  45.0  45000.0         IT
3   NaN  40000.0      Sales
4  35.0  34000.0         HR
5  25.0  26000.0         HR
6  46.0  56000.0         IT
7  43.0      NaN         HR
8  34.0  34000.0        NaN

In [2]:
df.shape

(9, 3)

In [3]:
df.tail()

    Age   Salary Department
4  35.0  34000.0         HR
5  25.0  26000.0         HR
6  46.0  56000.0         IT
7  43.0      NaN         HR
8  34.0  34000.0        NaN

In [4]:
print("missing values : ")
print(df.isnull().sum(),"\n")

missing values :
Age           1
Salary        1
Department    1
dtype: int64

In [5]:
df_dropped_cols = df.dropna(axis=1)
print("dropped cols \n",df_dropped_cols)

dropped cols
 Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
df_pandas_filled = df.copy()
df_pandas_filled["Age"] = df_pandas_filled["Age"].fillna(df_pandas_filled["Age"].mean())
df_pandas_filled.head()

      Age   Salary Department
0  25.000  25000.0         HR
1  26.000  27000.0         IT
2  45.000  45000.0         IT
3  34.875  40000.0      Sales
4  35.000  34000.0         HR

In [7]:
df_pandas_filled1 = df.copy()
df_pandas_filled1["Salary"] = df_pandas_filled1["Salary"].fillna(df_pandas_filled1["Salary"].median())
df_pandas_filled1.head(10)

    Age   Salary Department
0  25.0  25000.0         HR
1  26.0  27000.0         IT
2  45.0  45000.0         IT
3   NaN  40000.0      Sales
4  35.0  34000.0         HR
5  25.0  26000.0         HR
6  46.0  56000.0         IT
7  43.0  34000.0         HR
8  34.0  34000.0        NaN

In [8]:
df_pandas_filled1["Age"] = df_pandas_filled1["Age"].fillna(df_pandas_filled1["Age"].mean())
df_pandas_filled1.head(10)

      Age   Salary Department
0  25.000  25000.0         HR
1  26.000  27000.0         IT
2  45.000  45000.0         IT
3  34.875  40000.0      Sales
4  35.000  34000.0         HR
5  25.000  26000.0         HR
6  46.000  56000.0         IT
7  43.000  34000.0         HR
8  34.000  34000.0        NaN

In [9]:
df_pandas_filled1["Department"] = df_pandas_filled1["Department"].fillna(df_pandas_filled1["Department"].mode()[0])
df_pandas_filled1.head(10)

      Age   Salary Department
0  25.000  25000.0         HR
1  26.000  27000.0         IT
2  45.000  45000.0         IT
3  34.875  40000.0      Sales
4  35.000  34000.0         HR
5  25.000  26000.0         HR
6  46.000  56000.0         IT
7  43.000  34000.0         HR
8  34.000  34000.0         HR