In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv('data.csv')
df.head()

    Age   Salary Department
0  25.0  25000.0         HR
1  26.0  27000.0         IT
2  45.0  45000.0         IT
3   NaN  40000.0      Sales
4  35.0  34000.0         HR

In [6]:
df.tail()

    Age   Salary Department
4  35.0  34000.0         HR
5  25.0  26000.0         HR
6  46.0  56000.0         IT
7  43.0      NaN         HR
8  34.0  34000.0        NaN

In [7]:
df.shape

(9, 3)

In [9]:
df.isnull().sum()

Age           1
Salary        1
Department    1
dtype: int64

In [10]:
df.isnull()

     Age  Salary  Department
0  False   False       False
1  False   False       False
2  False   False       False
3   True   False       False
4  False   False       False
5  False   False       False
6  False   False       False
7  False    True       False
8  False   False        True

In [11]:
df_dropped_rows = df.dropna()
print(df_dropped_rows,"\n")

    Age   Salary Department
0  25.0  25000.0         HR
1  26.0  27000.0         IT
2  45.0  45000.0         IT
4  35.0  34000.0         HR
5  25.0  26000.0         HR
6  46.0  56000.0         IT

In [12]:
df_dropped_cols = df.dropna(axis=1)
print(df_dropped_cols,"\n")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [15]:
df_copy=df.copy()
df_copy['Age']=df_copy['Age'].fillna(df_copy['Age'].mean())
print(df_copy)

      Age   Salary Department
0  25.000  25000.0         HR
1  26.000  27000.0         IT
2  45.000  45000.0         IT
3  34.875  40000.0      Sales
4  35.000  34000.0         HR
5  25.000  26000.0         HR
6  46.000  56000.0         IT
7  43.000      NaN         HR
8  34.000  34000.0        NaN